plugins {
  id("com.android.application")
  kotlin("android")
  id("com.google.devtools.ksp")
}

android {
  namespace = "de.climatelabs.kmmsettings.android"
  compileSdk = 33
  defaultConfig {
    applicationId = "de.climatelabs.kmmsettings.android"
    minSdk = 26
    targetSdk = 33
    versionCode = 1
    versionName = "1.0"
  }
  buildFeatures {
    compose = true
  }
  composeOptions {
    kotlinCompilerExtensionVersion = "1.3.2"
  }
  packagingOptions {
    resources {
      excludes += "/META-INF/{AL2.0,LGPL2.1}"
    }
  }
  buildTypes {
    getByName("release") {
      isMinifyEnabled = false
    }
  }

  // Currently the code generated by KSP isn't automatically picked up, so we have to manually add it to the source set
  // https://github.com/google/ksp/issues/965
  // https://github.com/evant/kotlin-inject/issues/193
  sourceSets.getByName("debug").java.srcDir("build/generated/ksp/debug/kotlin")
  sourceSets.getByName("release").java.srcDir("build/generated/ksp/release/kotlin")
  sourceSets.getByName("testDebug").java.srcDir("build/generated/ksp/debugUnitTest/kotlin")
  sourceSets.getByName("androidTestDebug").java.srcDir("build/generated/ksp/debugAndroidTest/kotlin")
}

dependencies {
  implementation(project(":shared"))
  implementation("androidx.compose.ui:ui:1.2.1")
  implementation("androidx.compose.ui:ui-tooling:1.2.1")
  implementation("androidx.compose.ui:ui-tooling-preview:1.2.1")
  implementation("androidx.compose.foundation:foundation:1.2.1")
  implementation("androidx.compose.material:material:1.2.1")
  implementation("androidx.activity:activity-compose:1.5.1")
  implementation("me.tatarka.inject:kotlin-inject-runtime:0.5.1")
  ksp("me.tatarka.inject:kotlin-inject-compiler-ksp:0.5.1")
}
